export const CREATE_NOTE = "NOTE/CREATE_NOTE";
export const EDIT_NOTE = "NOTE/EDIT_NOTE";
export const OPEN_NOTE = "NOTE/OPEN_NOTE";
export const EDIT_CURRENT_NOTE = "NOTE/EDIT_CURRENT_NOTE";
export const SHOW_WORKSPACE = "WORKSPACE/SHOW_WORKSPACE";
export const HIDE_WORKSPACE = "WORKSPACE/HIDE_WORKSPACE";
